# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job_is_amazing:
    name: build that for arduino uno, boy
    # pick Windows for no particular reason.
    runs-on: windows-latest
    strategy:
      matrix:
        arduino-platform: ["arduino:samd", "arduino:avr"]
        include:
          # This works like this: when the platform is "arduino:samd", the
          # variable fqbn is set to "arduino:samd:nano_33_iot".
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:nano_33_iot"
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
  
    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
 
      - name: Compile Sketch
        # the project to compile should probably also be a matrix. Well..
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./DS_oled
